Add user group attributes
geosolutions-it/geostore pull request #278
Opened 2022-06-06 12:08 UTC by taba90

- add user groups attributes management to geostore.
- add migration scripts and update schema creation scripts.

2022-10-06 14:56 UTC, offtherailz requested changes

2022-10-06 14:56 UTC, offtherailz commented on doc/sql/migration/h2/h2-migration-from-v.1.5.0-to-v1.9.0
> +create table gs_user_group_attribute (
need to remame these files and update to 1.10.0 (or whatever).

2022-12-14 14:54 UTC, taba90 commented
thanks for the review @offtherailz feedback applied.

2022-12-14 16:25 UTC, offtherailz approved these changes
LGTM. Maybe before to merge we need to set the proper migration guidelines to update the database. 
I have this PR for UI https://github.com/geosolutions-it/MapStore2/pull/7875
I'll do another PR tomorrow to update migration guidelines.

2022-12-14 16:43 UTC, merged