- Making sure we do not overwrite existing scopes explicitly set by …
geosolutions-it/geostore pull request #357
Opened 2024-07-02 14:38 UTC by afabiani

…configuration

(cherry picked from commit 59b7b63294a3402b8652135451c5d8ca68d2baf9)

2024-07-09 10:41 UTC, offtherailz requested changes
Can not test. 
- [x] If I do not set scopes, it rises an exception (see inline comment)
- [ ] If I set scopes, `oidcOAuth2Config.scopes=openid,profile,groups`, I have a `No access token found on callback request. ` without any additional logging.

Scope should be optional, and when we have errors, we should have a proper logging to be able to identify the problem and possibly be able to fix the configuration issues, without the needing to inspect the code everytime. 
This issue without any logging happened a lot of times, and findi out the reason is extremely expensive in terms of time and resources,

2024-07-09 10:41 UTC, offtherailz commented on src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/security/oauth2/DiscoveryClient.java
> +                                    mergedScopes.addAll(Arrays.asList(conf.getScopes().split(",")));
I have a `NullPointerException` when I do not set scopes.

```
	... 30 more
Caused by: java.lang.NullPointerException
	at it.geosolutions.geostore.services.rest.security.oauth2.DiscoveryClient.lambda$autofill$6(DiscoveryClient.java:114) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at it.geosolutions.geostore.services.rest.security.oauth2.DiscoveryClient.autofill(DiscoveryClient.java:107) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectFilter.<init>(OpenIdConnectFilter.java:71) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectSecurityConfiguration.oidcOpenIdFilter(OpenIdConnectSecurityConfiguration.java:145) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectSecurityConfiguration$$EnhancerBySpringCGLIB$$9ded83d5.CGLIB$oidcOpenIdFilter$3(<generated>) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectSecurityConfiguration$$EnhancerBySpringCGLIB$$9ded83d5$$FastClassBySpringCGLIB$$e4b2836b.invoke(<generated>) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.18.jar:5.3.18]
	at it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectSecurityConfiguration$$EnhancerBySpringCGLIB$$9ded83d5.oidcOpenIdFilter(<generated>) ~[geostore-rest-impl-2.2-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

2024-07-09 12:35 UTC, afabiani commented
@offtherailz NPE fix pushed, for the second statement, rise the log level to DEBUG or check the Keycloack service log.

2024-07-09 16:07 UTC, offtherailz requested changes
- [ ] Logging for callback error (and errorDescription) in `/callback` endpoint
- [ ] Support for `groupMapping` as for keycloak

2024-07-11 15:21 UTC, offtherailz approved these changes

2024-07-11 15:21 UTC, merged